steps:
- name: gcr.io/cloud-builders/go
  args: ['install', 'report']
  env: ['PROJECT_ROOT=report']
- name: gcr.io/cloud-builders/docker
  args: ['build', '--tag=gcr.io/$PROJECT_ID/report', '.']

images: ['gcr.io/$PROJECT_ID/report']
